-- V1__create_users.sql
-- Creates the users table. Referenced by all other tables.
-- MySQL version: UUID stored as CHAR(36), generated by application.

CREATE TABLE users (
    id            CHAR(36)     NOT NULL,
    name          VARCHAR(255) NOT NULL,
    email         VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255),
    role          VARCHAR(20)  NOT NULL DEFAULT 'USER',
    created_at    DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at    DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),

    CONSTRAINT pk_users       PRIMARY KEY (id),
    CONSTRAINT uk_users_email UNIQUE      (email),
    CONSTRAINT chk_users_role CHECK       (role IN ('USER', 'ADMIN'))
);

CREATE INDEX idx_users_email ON users (email);
